// examples/single-page-application/react-app/src/App.js
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom'

import './App.css';
import Markers from './examples/markers';

class App extends Component {
  render() {
    return (
      <Router>
        <div className="App">
          <p>This is an app meant to demonstrate how to use the ros3djs module in a Single Page Application</p>
          <p>Examples:</p>
          <ul>
            <li><Link to="/examples/markers">Markers</Link></li>
          </ul>

          <div id="examples">
              <div>
                <Route exact path="/examples/markers" component={Markers} />
              </div>
          </div>
        </div>
      </Router>
    );
  }
}

export default App;

// examples/single-page-application/vue-app/src/App.vue
<template>
  <div id="app">
    <p>This is an app meant to demonstrate how to use the ros3djs module in a Single Page Application</p>
    <p>Examples:</p>
    <ul>
      <li><router-link to="markers">Markers</router-link></li>
    </ul>

    <div id="examples">
      <router-view/>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: left;
  color: #2c3e50;
  margin: 1em;
}

li {
  list-style-type: none;
}

#examples {
  box-shadow:
    rgba(10, 16, 20, 0.24) 0px 2px 2px,
    rgba(10, 16, 20, 0.12) 0px 0px 2px;
  padding: 1em;
}
</style>
